### ISSUE TITLE
Binary release

### ISSUE THREAD

**Issue by slimshader** [flecs-hub/flecs-cs#40]
Hi,

is the "from source" the only way to get flecs-cs? Are releases planned for dlls that could be just dropped into the project as dependency?

**Comment by lithiumtoast** [comment]
Hello @slimshader,

> is the "from source" the only way to get flecs-cs?

Technically no, in the GitHub Actions I have the native libraries built through CI/CD. 

<img width="809" alt="Screen Shot 2022-08-04 at 09 52 51" src="https://user-images.githubusercontent.com/519592/182864635-1e8c207c-71e7-421a-b736-bb172bbe2b9b.png">

You can download the artifact as a `.zip`.

<img width="907" alt="Screen Shot 2022-08-04 at 09 55 07" src="https://user-images.githubusercontent.com/519592/182864841-84477158-cd67-4426-9e9b-7d806f10bd23.png">

I have the idea rolling in my head to use a special case of NuGet packages for packaging only the shared object binaries for runtime, no code. This is something Microsoft does for example with https://www.nuget.org/packages/libclang.runtime.win-x64/.

<img width="760" alt="Screen Shot 2022-08-04 at 09 58 15" src="https://user-images.githubusercontent.com/519592/182865636-6e136049-2501-4544-8d98-ae600b6294ed.png">

The NuGet package path of "runtimes/[RID]/native/[LIBRARY][.so|.dll|.dylib]" is special and is handled by .NET when searching for loading libraries at runtime in a special way according to the RID that matches for the runtime.

The problem for Microsoft is that these files are relatively large and have expressed that delivering them through NuGet is not ideal if the frequency is too frequent. I'm still trying to grasp what would the appropriate timeframe be for uploading NuGet packages of the binaries to NuGet. That would most likely dictate a release cycle.

**Comment by slimshader** [comment]
Sorry for late reply, I only had time now to go back to trying Flecs-cs again. With your help I was able to run C# example pojects with no problems so thank you, unfortunately I was not so lucky after importing flecs-cs into Unity, which I reported in other issue.

**Comment by lithiumtoast** [comment]
Hey @slimshader, I'm experimenting with NuGet packages at this time which would cover binary release. See the `README.md` of the repo for more details.
