### ISSUE TITLE
Missing flecs.h

### ISSUE THREAD

**Issue by joness95** [flecs-hub/flecs-cs#83]
When building the latest main, the shellscript throws this:

rary/main.sh': Running...
-- Building for: Visual Studio 17 2022
-- Selecting Windows SDK version 10.0.19041.0 to target Windows 10.0.19044.
-- The C compiler identification is MSVC 19.33.31630.0
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: C:/Program Files/Microsoft Visual Studio/2022/Community/VC/Tools/MSVC/14.33.31629/bin/Hostx64/x64/cl.exe - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Configuring done
-- Generating done
-- Build files have been written to: C:/Users/.../source/repos/.../ECSTest/flecs-cs/build/cmake-build-release-flecs
MSBuild version 17.3.1+2badb37d1 for .NET Framework
  Checking Build System
  Building Custom Rule C:/Users/.../source/repos/.../ECSTest/flecs-cs/src/c/production/flecs/CMakeLists.txt
  flecs_pinvoke.c
C:\Users\...\source\repos\...\ECSTest\flecs-cs\src\c\production\flecs\include\flecs_pinvoke.h(2,1): fatal  error C1083: Datei (Include) kann nicht geöffnet werden: "flecs.h": No such file or directory [C:\Users\...\source\repos\....\ECSTest\flecs-cs\build\cmake-build-release-flecs\flecs.vcxproj]
'/c/Users/.../source/repos/.../ECSTest/flecs-cs/ext/scripts/c/library/main.sh': Success.

**Comment by lithiumtoast** [comment]
Weird, the GitHub actions are passing. Did you clone with submodules?

**Comment by lithiumtoast** [comment]
Closing as resolved; `flecs.h` belongs to the submodule. If the submodule is not setup `flecs.h` will be missing.
